Further XC_functionals added
ondracka/nomad-parser-openmx pull request #15
Opened 2021-05-27 04:32 UTC by Mdmorshadurrahman

2021-05-27 06:32 UTC, ondracka commented on openmxparser/parser.py
> +            if mainfile_parser.get('scf_XcType').upper() == 'GGA-PBE':
There is no need to call the get method again. We already have the results in scf_XcType. Same for the cases below.

2021-05-27 06:33 UTC, ondracka commented on openmxparser/parser.py
> +            elif mainfile_parser.get('scf_XcType').upper() == 'LDA' or 'LSDA-CA':
This is not doing what you think it does, the `or 'LSDA-CA'` part will always evaluate to True

2021-05-27 06:56 UTC, ondracka commented
So first of all this is not based on top of the latest ondracka/master, please rebase.

Also instead of this quite big if-elif-... construct, the code could be simplified with a usage of dictionary like this:
```
xc_functional_dictionary = {
    'GGA-PBE': ['GGA_C_PBE','GGA_X_PBE'],
    'LDA': ['LDA_X', 'LDA_C_PZ']
    ......
}
```

and than do just
```
scf_XcType = mainfile_parser.get('scf_XcType')
for xc in xc_functional_dictionary[scf_XcType]:
    method.m_create(xc_functionals).XC_functional_name = xc
```

It looks also like we don't need the .upper() method as the functional names must be uppercase otherwise OpenMX complains (but this was my fault for not checking earlier), so we could in theory just add key "None: ['LDA_X', 'LDA_C_PZ']" to the dictionary as well and get rid of the if `if scf_XcType is not None:` check.

Tests are not needed right now as we don't have any testcase which exercises this. I'll try to add something.

2021-05-27 06:59 UTC, ondracka requested changes
Actually I'll try to commit a test case for the LDA stuff in a moment, so rebase on top of it and then also add tests.

2021-05-27 07:02 UTC, ondracka commented on openmxparser/parser.py
> +            if mainfile_parser.get('scf_XcType').upper() == 'GGA-PBE':
This comment might be obsolete if we go for the dictionary-based rewrite. Same below.

2021-05-27 18:19 UTC, ondracka commented
Hi Joseph,

it looks like you are a bit lost at the moment and the rebase went really wrong. Instead of trying to fix it in git which could be tricky, it might be the best if you:
1) save the changes (the final files openmx/parser.py and tests/test_parser.py files somewhere outside the git)
2) delete this branch altogether
3) switch to your master
4) rebase to latest ondracka/master
5) make a new branch (for example XC_functionals2) and switch to it
6) copy the relevant parts form the backed-up files
7) create a new commit
8) push to your repo
9) create a completely new pull request

Let me know if you run into issues.

2021-05-27 23:57 UTC, Mdmorshadurrahman commented
> So first of all this is not based on top of the latest ondracka/master, please rebase.
> 
> Also instead of this quite big if-elif-... construct, the code could be simplified with a usage of dictionary like this:
> 
> ```
> xc_functional_dictionary = {
>     'GGA-PBE': ['GGA_C_PBE','GGA_X_PBE'],
>     'LDA': ['LDA_X', 'LDA_C_PZ']
>     ......
> }
> ```
> 
> and than do just
> 
> ```
> scf_XcType = mainfile_parser.get('scf_XcType')
> for xc in xc_functional_dictionary[scf_XcType]:
>     method.m_create(xc_functionals).XC_functional_name = xc
> ```
> 
> It looks also like we don't need the .upper() method as the functional names must be uppercase otherwise OpenMX complains (but this was my fault for not checking earlier), so we could in theory just add key "None: ['LDA_X', 'LDA_C_PZ']" to the dictionary as well and get rid of the if `if scf_XcType is not None:` check.
> 
> Tests are not needed right now as we don't have any testcase which exercises this. I'll try to add something.

If we do not use `if scf_XcType is not None:`  then how can we detect **key** when there is no 'scf_XcType'.
and for `method.m_create(xc_functionals).XC_functional_name = xc` , will it be able to place both values in two individial XC_functionals1 and 2?

2021-05-28 05:51 UTC, ondracka commented
> If we do not use `if scf_XcType is not None:` then how can we detect **key** when there is no 'scf_XcType'.
> and for `method.m_create(xc_functionals).XC_functional_name = xc` , will it be able to place both values in two individial XC_functionals1 and 2?

If there is no 'scf.XcType' in the out file defined, i.e., the `scf_XcType = mainfile_parser.get('scf_XcType') ` is None. 
The next line is `for xc in xc_functional_dictionary[scf_XcType]:`. Now, `xc_functional_dictionary` is a dictionary, see:
https://www.w3schools.com/python/python_dictionaries.asp
so if we define it like this:
xc_functional_dictionary = {
    'GGA-PBE': ['GGA_C_PBE','GGA_X_PBE'],
    'LDA': ['LDA_X', 'LDA_C_PZ'],
    ..... orther LSDA functionals....
    None: ['LDA_X', 'LDA_C_PZ']
}
it returns the value for whatever key is specified. None is nothing special in this case, and we can use it as a key: https://stackoverflow.com/questions/7030029/is-it-reasonable-to-use-none-as-a-dictionary-key-in-python

The actual dictionary values are lists with two items. So when we do 
`for xc in xc_functional_dictionary[scf_XcType]:`
it is essentially a loop over the two items of the corresponding list for the specific key from the dictionary, so the following line `method.m_create(xc_functionals).XC_functional_name = xc` is called once for every values from the list and you get the desired behaviour.

2021-05-28 14:31 UTC, Mdmorshadurrahman commented
> > If we do not use `if scf_XcType is not None:` then how can we detect **key** when there is no 'scf_XcType'.
> > and for `method.m_create(xc_functionals).XC_functional_name = xc` , will it be able to place both values in two individial XC_functionals1 and 2?
> 
> If there is no 'scf.XcType' in the out file defined, i.e., the `scf_XcType = mainfile_parser.get('scf_XcType') ` is None.
> The next line is `for xc in xc_functional_dictionary[scf_XcType]:`. Now, `xc_functional_dictionary` is a dictionary, see:
> https://www.w3schools.com/python/python_dictionaries.asp
> so if we define it like this:
> xc_functional_dictionary = {
> 'GGA-PBE': ['GGA_C_PBE','GGA_X_PBE'],
> 'LDA': ['LDA_X', 'LDA_C_PZ'],
> ..... orther LSDA functionals....
> None: ['LDA_X', 'LDA_C_PZ']
> }
> it returns the value for whatever key is specified. None is nothing special in this case, and we can use it as a key: https://stackoverflow.com/questions/7030029/is-it-reasonable-to-use-none-as-a-dictionary-key-in-python
> 
> The actual dictionary values are lists with two items. So when we do
> `for xc in xc_functional_dictionary[scf_XcType]:`
> it is essentially a loop over the two items of the corresponding list for the specific key from the dictionary, so the following line `method.m_create(xc_functionals).XC_functional_name = xc` is called once for every values from the list and you get the desired behaviour.

I understood the behaviour of `method.m_create(xc_functionals).XC_functional_name = xc`  and i am doing so but my only silly query is as we have two XC_functionals like:
        section_XC_functionals1 = method.m_create(xc_functionals)
        section_XC_functionals2 = method.m_create(xc_functionals) 
so, will both functional1 and functional2 will get desired values accordingly here?

2021-05-28 18:24 UTC, ondracka commented
> I understood the behaviour of `method.m_create(xc_functionals).XC_functional_name = xc` and i am doing so but my only silly query is as we have two XC_functionals like:
> section_XC_functionals1 = method.m_create(xc_functionals)
> section_XC_functionals2 = method.m_create(xc_functionals)
> so, will both functional1 and functional2 will get desired values accordingly here?

Yes, it will work, section_XC_functionals1 and section_XC_functionals2 are just some arbitrary temporary variables, so it doesn't matter if we assign to method.m_create(xc_functionals).XC_functional_name directly.

2021-05-29 14:54 UTC, closed without merging