Smearing method
ondracka/nomad-parser-openmx pull request #16
Opened 2021-05-27 05:23 UTC by Mdmorshadurrahman

2021-05-27 07:19 UTC, ondracka requested changes
Please rebase on top of ondracka/master and fix it according to the review.

I'll also commit a testcase with non/default ElectronicTemperature, so please test it as well.

2021-05-27 07:19 UTC, ondracka commented on openmxparser/parser.py
> +            method.smearing_width = 4.14194634200767E-21
I don't like using magic numbers in the code like this, one should use the `300 * units.kelvin` instead
However there is actually a bug in the method.smearing_width metainfo definition as is is currently unitless, so we need some tricks: `(300 * units.kelvin).to_base_units().magnitude`.

2021-05-27 07:19 UTC, ondracka commented on openmxparser/parser.py
> +            method.smearing_width = scf_ElectronicTemperature
You are missing a conversion to joule here, see the comment below how to do it properly.

2021-05-27 07:19 UTC, ondracka commented on openmxparser/parser.py
> +        scf_ElectronicTemperature = mainfile_parser.get('scf.ElectronicTemperature')
This is broken. You call get for 'scf.ElectronicTemperature' buit the quantity is actually defined as 'scf_ElectronicTemperature' so you get always None. However because the default is actually the same as the values in our two test cases (300K) the test manage to pass.

2021-05-27 07:19 UTC, ondracka commented on tests/test_parser.py
> +    assert method.smearing_width == 4.14194634200767E-21
Some as above, don't use magic numbers. Also please use approx() when comparing floating point values.

2021-05-29 14:54 UTC, closed without merging

2021-05-30 00:08 UTC, Mdmorshadurrahman commented on openmxparser/parser.py
> +            method.smearing_width = scf_ElectronicTemperature
if i use this method `def K_to_J(value):
    return (value * units.joules).to_base_units().magnitude` 
will it work for converting from kelvin to Joules or can i do the conversion manually?