modification for automatic tests run
ondracka/nomad-parser-openmx pull request #8
Opened 2021-05-03 01:58 UTC by Mdmorshadurrahman

Modified code formatting via **pycodestyle** for automatic test ( ignoring error E501(^) )

2021-05-03 05:19 UTC, ondracka commented on openmxparser/parser.py
> +    Quantity('scf_SpinPolarization', r'scf.SpinPolarization          (\S+)', repeats=False)
You have multiple spaces here. This won't work when user adds another amount of spaces. Please use \s+ for one or more of any whitespace characters

2021-05-03 05:22 UTC, ondracka commented on openmxparser/parser.py
>          md_steps = mainfile_parser.get('md_step')
You have multiple print lines there. While it is OK to use that for development and debuging, this should not be here for final commit.

2021-05-03 05:23 UTC, ondracka commented on openmxparser/parser.py
This is unnecessary commit, the prints should be removed instead.

2021-05-03 06:15 UTC, ondracka commented
Hi Joseph,

thanks for the pull request. This is a good start but there are still multiple issues:

1. the commits are not doing what they claim they do in the commit message, for example "modification for automatic tests run" has the structure parsing stuff inside.
2. The tests are not actually fixed. See the run results https://github.com/ondracka/nomad-parser-openmx/runs/2489512273 I tried to make the tests run automatically fro new pull requests, so you can see what is failing but I'm not sure if I managed to do that.
3. There are some debug prints forgotten
4. There are no tests. There should be tests for every addition to the metainfo, see commit https://github.com/ondracka/nomad-parser-openmx/commit/cae18750c59fa7b2aefcd1a595099f87f0fc7d1f for example where tests were added together with the code.
5. Other random minor issues, see inline comments.

2021-05-03 06:18 UTC, ondracka requested changes
As far as I can see this commit does not fix the tests but rather adds the structure parsing stuff we did during the last zoom call.

2021-05-03 06:18 UTC, ondracka commented on openmxparser/metainfo.py
> +    # program_basis_set_type = Quantity(type=str, description= 'should be always "Numeric AOs"')
Don't commit dead code.

2021-05-03 06:19 UTC, ondracka commented
I'm still learning the github review process, so if something is unclear please let me know.

2021-05-03 17:19 UTC, Mdmorshadurrahman commented on openmxparser/parser.py
> +    Quantity('scf_SpinPolarization', r'scf.SpinPolarization          (\S+)', repeats=False)
ok corrected.

2021-05-03 17:24 UTC, Mdmorshadurrahman commented on openmxparser/parser.py
>          md_steps = mainfile_parser.get('md_step')
corrected.

2021-05-03 17:24 UTC, Mdmorshadurrahman commented on openmxparser/parser.py
Removed.

2021-05-10 07:00 UTC, ondracka commented
Any updates here?

2021-05-10 12:02 UTC, Mdmorshadurrahman commented
> Any updates here?

As I am also not really good in GitHub, I struggled a bit with branch merging but failed so now I will make a new pull request by today otherwise I might get in more complexity.

2021-05-11 18:38 UTC, ondracka commented
Most of this pull request is now either committed through the other pull request or obsolete. I'm closing it now.

2021-05-11 18:38 UTC, closed without merging